DROP TABLE dbo.StudentResources;
DROP TABLE dbo.TutoringAppts;
DROP TABLE dbo.Classes;
DROP TABLE dbo.TutorSchedule;
DROP TABLE dbo.Admins;
DROP TABLE dbo.Students;
DROP TABLE dbo.Tutors;
DROP TABLE dbo.Professors;
DROP TABLE dbo.BTTUsers;